var toDoVariables = {
  btnPlus: document.querySelector(".btn"),
  input: document.querySelector(".input"),
  ul: document.querySelector("ul"),
  icons: document.querySelectorAll(".icon"),
  ies: document.querySelectorAll("i"),
  lists: document.getElementsByClassName("list-item"),
  deleteBtn: document.getElementsByClassName("delete"),
  btnAll: document.querySelector(".filter-link--all"),
  filterBtns: document.querySelectorAll(".filter-link"),
  sortBtns: document.querySelectorAll(".sort-btn"),
  btnActive: document.querySelector(".filter-link--active"),
  btnCompleted: document.querySelector(".filter-link--completed"),
  btnAlphaDown: document.querySelector(".fa-sort-alpha-down"),
  btnAlphaDownAlt: document.querySelector(".fa-sort-alpha-down-alt"),
  pagination: document.querySelector(".pagination"),
  paginationItems: document.getElementsByClassName("pagination-item"),
  paginationItems2: document.querySelectorAll("pagination-item"),
};
